### ISSUE TITLE
Buildng source sign error

### ISSUE THREAD

**Issue by giacomopiva** [synapse/source#3]
I'm getting this error: 

Signing for "Source" requires selecting either a development team or a provisioning profile. Select a development team or a provisioning profile in the project editor.

I don't have a Mac Developer program account... what should I do?

**Comment by synapse** [comment]
Choose `Do not sign` in XCode, it should work.

http://stackoverflow.com/questions/12362778/what-is-the-purpose-of-dont-code-sign-value-in-xcode-build-settings-cod
